### ISSUE TITLE
[ENHANCEMENT] MathInput-Quill component : change font

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/platon-front#81]
Première suggestion d'amélioration pour le composant.

La police utilisée par MathQuill (Symbola) est différente de celle utilisée par MathJax (MathJax TeX), ce qui, dans un même exercice, donne des polices différentes dans l'énoncé et dans le champ de réponse. Je propose donc d'utiliser la police de MathJax dans le champ de saisie du composant MathInput-Quill.

Dans mon "composant bricolé", j'ai ajouté ça dans le fichier de style et ça marchait (MJXc-TeX-math-Iw est la fonte italique de la police MathJax TeX).

```css
.mq-math-mode .mq-nonSymbola, .mq-math-mode .mq-text-mode, .mq-math-mode var {
    font-family: "MJXc-TeX-math-Iw", "Times New Roman", Symbola, serif;
    line-height: 0.9;
}
```
